"""JSON Schema for the probe-spec YAML format.

Editors use it to autocomplete and validate spec files (VS Code's YAML
extension, JetBrains), and the CLI prints it. The committed copy lives at
``schema/probe-spec.schema.json`` and is regenerated by
``scripts/generate_schema.py``::

    from undercurrent.spec import json_schema
    schema = json_schema()   # a Draft 2020-12 schema, as a plain dict

The schema starts from pydantic's own schema for
`ProbeSpecFile` and adds what pydantic can't
express: descriptions and examples, the deprecated input aliases, value
bounds enforced by field validators, and the cross-field rules enforced by
model validators. It is a strict subset of what the parser accepts *except*
for ``position``: its ``pattern`` follows the grammar but can't check that a
slice's stop is greater than its start, so the parser stays the authority.
"""

from __future__ import annotations

import copy
from typing import Any

from .schema import DEPRECATED_KEY_ALIASES, ProbeSpecFile

SCHEMA_DIALECT = "https://json-schema.org/draft/2020-12/schema"
SCHEMA_ID = "https://raw.githubusercontent.com/wrynx/undercurrent/main/schema/probe-spec.schema.json"

#: Mirrors the regexes in `undercurrent.spec.position` (the parser
#: strips surrounding whitespace first). Doesn't check slice ordering.
POSITION_PATTERN = (
    r"^\s*(?:-?\d+"
    r"|prompt\[-?\d+\](?:[+-]\d+)?"
    r"|generated\[(?:-?\d+|\*|\d+:\d*)\](?:[+-]\d+)?)\s*$"
)

#: The continuous forms ('generated[*]' and slices), which 'stride' and
#: 'until' require.
_CONTINUOUS_POSITION_PATTERN = r"^\s*generated\[(?:\*|\d+:\d*)\](?:[+-]\d+)?\s*$"

_POSITION_DESCRIPTION = (
    "Which token position(s) to capture. One of:\n"
    "- an integer (or integer string): absolute index into the full prompt + generated sequence, e.g. 5\n"
    "- 'prompt[i]': the i-th prompt token; negative counts from the end ('prompt[-1]' is the last prompt token)\n"
    "- 'generated[i]': the i-th generated token; 'generated[-1]' is the last one\n"
    "- 'generated[*]': every generated token (continuous)\n"
    "- 'generated[start:]' or 'generated[start:stop]': generated tokens in [start, stop) (continuous; stop > start)\n"
    "Any non-integer form may end in an offset such as '+1' or '-2', e.g. 'prompt[-1]+1' "
    "(one token past the last prompt token). 'stride' and 'until' only apply to continuous selectors."
)

_ENUM_DESCRIPTIONS: dict[str, str] = {
    "TensorType": (
        "Which tensor to capture at each layer: 'residual_stream' (decoder-layer output), 'attn_out', "
        "'mlp_out', 'kv' (the KV cache), or 'final_norm' (the model's final norm output, after the last "
        "decoder layer; distinct from 'residual_stream' at the last layer, which is pre-norm)."
    ),
    "ProbeKind": (
        "'single_shot': the probe sees one activation and returns a result. "
        "'trajectory': the probe keeps state across positions (required for execution_mode 'async')."
    ),
    "ExecutionMode": (
        "'inline': the probe runs on the generation path and can intervene. "
        "'async': the activation is queued and probed off the hot path (trajectory probes only)."
    ),
    "UntilKind": "When a continuous capture stops: at generation end, after a fixed count, or at a stop token.",
    "InterventionMode": (
        "'reject' (default): no wait-for-decision contract. 'block_until_signal': the router waits up to "
        "timeout_ms for the probe before generation proceeds (requires timeout_ms)."
    ),
    "TimeoutAction": (
        "What block_until_signal falls back to when timeout_ms elapses or the probe raises: "
        "'continue' generation or 'abort' it."
    ),
}

_POINT_DESCRIPTIONS: dict[str, str] = {
    "name": "Unique name for this extraction point within the spec file.",
    "layers": "Layer index (0-based) or a non-empty list of layer indices to capture at.",
    "tensor_type": _ENUM_DESCRIPTIONS["TensorType"],
    "position": _POSITION_DESCRIPTION,
    "stride": (
        "Only match every Nth position within a continuous position selector ('generated[*]' or a slice). Must be >= 1."
    ),
    "until": "When a continuous capture stops. Only valid with a continuous position selector.",
    "probe_type": "Name of the registered probe that consumes these activations, e.g. 'linear_probe'.",
    "probe_kind": _ENUM_DESCRIPTIONS["ProbeKind"],
    "execution_mode": _ENUM_DESCRIPTIONS["ExecutionMode"],
    "queue_depth": (
        "Bounded queue size for this point's async worker. Only valid with execution_mode 'async'; "
        "omit it to use the router's default. Must be >= 1."
    ),
    "intervention": (
        "Intervention policy for this point. Omit it to use the router's default. "
        "async points may only use the default (mode 'reject')."
    ),
    "probe_args": (
        "Extra constructor keyword arguments for this point's probe, merged over the router's "
        "probe_kwargs (this point wins)."
    ),
}

_POLICY_DESCRIPTIONS: dict[str, str] = {
    "mode": _ENUM_DESCRIPTIONS["InterventionMode"],
    "timeout_ms": "How long to wait for the probe, in milliseconds (>= 1). Required for, and only valid with, mode 'block_until_signal'.",
    "on_timeout": _ENUM_DESCRIPTIONS["TimeoutAction"],
}

_EXAMPLES: dict[str, list[Any]] = {
    "tensor_type": ["residual_stream", "mlp_out", "final_norm"],
    "position": ["prompt[-1]", "generated[*]", "generated[5:20]", "prompt[-1]+1", 5],
    "probe_kind": ["single_shot", "trajectory"],
}

#: Deprecated input key -> canonical key, including the ``every_n`` alias
#: of ``stride`` (a pydantic validation alias rather than a renamed key).
_DEPRECATED_ALIASES: dict[str, str] = {**DEPRECATED_KEY_ALIASES, "every_n": "stride"}


def json_schema() -> dict[str, Any]:
    """Return the JSON Schema (Draft 2020-12) for probe-spec YAML files.

    The result is a fresh dict each call, with a deterministic key order,
    so ``json.dumps(json_schema(), indent=2)`` is byte-stable.
    """
    raw = ProbeSpecFile.model_json_schema(mode="validation")
    defs = raw.pop("$defs")

    for enum_name, description in _ENUM_DESCRIPTIONS.items():
        defs[enum_name]["description"] = description

    _patch_extraction_point(defs["ExtractionPointSpec"])
    _patch_intervention_policy(defs["InterventionPolicySpec"])

    raw["properties"]["version"]["description"] = 'Spec format version (currently "1").'
    raw["properties"]["extraction_points"]["description"] = (
        "The extraction points: what to capture during inference and which probe consumes it."
    )
    raw.pop("title", None)
    raw.pop("description", None)

    schema: dict[str, Any] = {
        "$schema": SCHEMA_DIALECT,
        "$id": SCHEMA_ID,
        "title": "Undercurrent probe spec",
        "description": (
            "Extraction-point spec for Undercurrent, Wrynx's activation-probing platform: which tensors to "
            "capture at which layers and token positions during LLM inference, and which probe consumes them."
        ),
        **raw,
        "$defs": {name: defs[name] for name in sorted(defs)},
    }
    return copy.deepcopy(schema)


def _patch_extraction_point(point: dict[str, Any]) -> None:
    props = point["properties"]
    for field, description in _POINT_DESCRIPTIONS.items():
        props[field].pop("title", None)
        props[field]["description"] = description
    for field, examples in _EXAMPLES.items():
        props[field]["examples"] = examples

    for field in ("name", "probe_type"):
        # Mirrors ExtractionPointSpec._non_empty: not empty or all-whitespace.
        props[field]["pattern"] = r"\S"

    non_negative = {"type": "integer", "minimum": 0}
    props["layers"]["anyOf"] = [non_negative, {"type": "array", "items": non_negative, "minItems": 1}]
    props["position"]["anyOf"] = [{"type": "integer"}, {"type": "string", "pattern": POSITION_PATTERN}]
    for field in ("stride", "queue_depth"):
        props[field]["anyOf"] = [{"type": "integer", "minimum": 1}, {"type": "null"}]

    # Deprecated aliases: still valid (the parser accepts them with a
    # DeprecationWarning, and additionalProperties is false, so they must be
    # declared) but flagged so editors don't suggest them. `doNotSuggest` and
    # `deprecationMessage` are VS Code / yaml-language-server extensions.
    for old, new in _DEPRECATED_ALIASES.items():
        props[old] = {
            **{k: v for k, v in props[new].items() if k not in ("description", "examples")},
            "description": f"Deprecated: use '{new}' instead.",
            "deprecated": True,
            "doNotSuggest": True,
            "deprecationMessage": f"'{old}' is deprecated; rename it to '{new}'.",
        }

    required = point.pop("required")
    point["required"] = [field for field in required if field not in DEPRECATED_KEY_ALIASES.values()]
    all_of: list[dict[str, Any]] = []
    for old, new in _DEPRECATED_ALIASES.items():
        if new in required:
            # Exactly one of the canonical key and its deprecated alias.
            all_of.append({"oneOf": [{"required": [new]}, {"required": [old]}]})
        else:
            all_of.append({"not": {"required": [new, old]}})

    # Cross-field rules from ExtractionPointSpec's model validators.
    all_of += [
        {
            "if": {"required": ["execution_mode"], "properties": {"execution_mode": {"const": "async"}}},
            "then": {
                "properties": {
                    "probe_kind": {"const": "trajectory"},
                    "intervention": {
                        "anyOf": [{"type": "null"}, {"properties": {"mode": {"const": "reject"}}}],
                    },
                },
            },
        },
        {
            "if": {"required": ["queue_depth"], "properties": {"queue_depth": {"type": "integer"}}},
            "then": {
                "required": ["execution_mode"],
                "properties": {"execution_mode": {"const": "async"}},
            },
        },
    ]
    for field, present in (
        ("stride", {"type": "integer"}),
        ("every_n", {"type": "integer"}),
        ("until", {"type": "string"}),
    ):
        all_of.append(
            {
                "if": {"required": [field], "properties": {field: present}},
                "then": {"properties": {"position": {"type": "string", "pattern": _CONTINUOUS_POSITION_PATTERN}}},
            }
        )
    point["description"] = "One extraction point: what to capture, where, and which probe consumes it."
    point["allOf"] = all_of


def _patch_intervention_policy(policy: dict[str, Any]) -> None:
    policy["description"] = (
        "Intervention policy: whether the router waits for this point's probe before generation proceeds."
    )
    props = policy["properties"]
    for field, description in _POLICY_DESCRIPTIONS.items():
        props[field].pop("title", None)
        props[field]["description"] = description
    props["timeout_ms"]["anyOf"] = [{"type": "integer", "minimum": 1}, {"type": "null"}]
    # Mirrors InterventionPolicySpec._check_combinations.
    policy["if"] = {"required": ["mode"], "properties": {"mode": {"const": "block_until_signal"}}}
    policy["then"] = {"required": ["timeout_ms"], "properties": {"timeout_ms": {"type": "integer"}}}
    policy["else"] = {
        "properties": {"timeout_ms": {"type": "null"}, "on_timeout": {"const": "continue"}},
    }
